#!/bin/bash -l

#Request 8 cores
#$ -pe omp 8
#
#Join output and error stream
#$ -j y
#
#Name your job
#$ -N doMC
#
#

# after we requested 8 slots with omp 8 option, 
# the variable NSLOTS is set to 8 and we can use it to pass the number
# of cores to the R script
#
module load R/3.2.3
Rscript domc.R $NSLOTS
