#!/bin/bash -l

# Submit job with the command: qsub rjob

# Set the runtime limit (default 12 hours):
#$ -l h_rt=12:00:00

# Specify the project
#$ -P krcs

# Send email when the job is done (default: no email is sent)
#$ -m e

# Give the job a name (default: script name)
#$ -N test

# Join the output and error streams
#$-j y

## end of qsub options

module load R/3.5.2

Rscript hello.R

# Alternatively, R script could be run as follwoing:
#R -q --vanilla < hello.R





