#!/bin/bash -l
#
# Submit job with the command: qsub SASjob
#
# To view the status of the job: qstat -u username
#
# Set the runtime limit (default 12 hours):
#$ -l h_rt=12:00:00
#
# Send email when the job is done (default: no email is sent)
#$ -m e
#
# Give the job a name (default: script name)
#$ -N helloWorld
#
# Join Error and Output streams
#$ -j y
#
## end of qsub options

module load sas/9.4
sas -noterminal helloWorld.sas

