#!/bin/bash -l

# Submit job with the command: qsub Statajob

# To view the status of the job: qstat -u username

# Set the runtime limit (default 12 hours):
#$ -l h_rt=12:00:00

# Send email when the job is done (default: no email is sent)
#$ -m e

# Give the job a name (default: script name)
#$ -N helloWorld

#Join output and error stream
#$-j y

## end of qsub options

echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "=========================================================="

module load stata/16
stata -b do helloWorld.do


echo "  "
echo "=========================================================="
echo "Job $JOB_NAME finished on : $(date)"
echo "=========================================================="
